"""Build the browser bundle from named view sources, without a Node dependency."""
from __future__ import annotations

import argparse
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DASHBOARD_SOURCE_ORDER = ("context", "formatting", "coverage", "forecast", "analysis", "bootstrap")


def build_dashboard_bundle(project_root: Path = PROJECT_ROOT) -> str:
    """Keep declarations in one private scope so existing static HTML stays valid."""
    parts = [(project_root / "dashboard" / "src" / f"{name}.js").read_text(encoding="utf-8").rstrip()
             for name in DASHBOARD_SOURCE_ORDER]
    return "// Generated by tools/build_dashboard_assets.py; edit dashboard/src/*.js.\n(async function () {\n" + "\n\n".join(parts) + "\n})();\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated bundle is stale")
    args = parser.parse_args()
    expected = build_dashboard_bundle()
    output = PROJECT_ROOT / "dashboard/assets/dashboard.js"
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit("Dashboard bundle is stale: run python tools/build_dashboard_assets.py")
        print("Dashboard bundle matches its view sources")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8")
        print(output.relative_to(PROJECT_ROOT))


if __name__ == "__main__":
    main()
